### ISSUE TITLE
Program has no effect on Nokia / Samsung phones

### ISSUE THREAD

**Issue by hurzl** [antweb/SilentBoot#2]
On a Nokia 7 with AndroidOne in any mode.

**Comment by ghost** [comment]
On my Samsung Galaxy A20e it doesn't work too. Any idea, how I can support to find out why?

**Comment by hurzl** [comment]
I guess it's because the app only changes some volume levels (in ShutdownReceiver) which can't work. 
I  would try to change do-not-disturb like described here for example:
https://stackoverflow.com/questions/31862753/android-how-to-turn-on-do-not-disturb-dnd-programmatically
Switching on do-not-disturb manually at least works for the Nokia.

**Comment by antweb** [comment]
A bit of a late answer, but it is likelier that the changes in intent behaviour are the problem. According to the docs, the app should simply no longer work on Android 9 or later. Although it comes down to manufacturer specific implementations once again, since I have received reports that it still does work on several phones even with Android 10.

See https://developer.android.com/reference/android/content/Intent#ACTION_SHUTDOWN

That being said, the PR mentioned above actually addresses both issues. I'm looking into it.

**Comment by antweb** [comment]
The latest [release](https://github.com/antweb/SilentBoot/releases/tag/v3.0) should fix this issue at least on some Nokias.

A tester reported that while Do Not Disturb is set correctly, his Nokia 5.3 still had a startup sound.

**Comment by antweb** [comment]
Feedback since the release has been positive. Closing this issue

**Comment by hurzl** [comment]
Still doesn't work (Nokia 7 plus)

**Comment by antweb** [comment]
Then I suspect a Nokia-specific problem here. Reopening this issue so we can collect findings.
So far I'm aware of problems on the Nokia 7 Plus and Nokia 5.3.

@hurzl you mentioned that manually enabling Do Not Disturb mutes the sound? Do you see the DND mode being enabled right before your phone turns off when using Silent Boot?

The current app version (3.0) toggles DND mode with `notificationManager.setInterruptionFilter(NotificationManager.INTERRUPTION_FILTER_NONE)`. So either there is another API required for Nokias or the call doesn't go through on time.

**Comment by ghost** [comment]
On my Galaxy A20e this app still doesn't work too.

**Comment by hurzl** [comment]
Yes it's silent with DND enabled. Here is what happens when enabling/disabling DND:

```
DND on:

11-07 15:20:10.332   811  5652 D AudioPolicyManagerCustom: setForceUse() usage 7, config 0, mPhoneState 0
11-07 15:20:10.334  2538  2766 I vol.Events: writeEvent mute_changed STREAM_SYSTEM true
11-07 15:20:10.342  2538  2766 I vol.Events: writeEvent external_ringer_mode_changed silent
11-07 15:20:10.348  1598  1598 V SettingsProvider: Notifying for 0: content://settings/global/zen_mode_config_etag
11-07 15:20:10.351  2538  2766 I vol.Events: writeEvent zen_mode_changed important_interruptions
11-07 15:20:10.352  1598  1598 V SettingsProvider: Notifying for 0: content://settings/global/zen_mode

DND off:

11-07 15:21:23.560   811  5652 D AudioPolicyManagerCustom: setForceUse() usage 7, config 0, mPhoneState 0
11-07 15:21:23.564  2538  2766 I vol.Events: writeEvent mute_changed STREAM_SYSTEM false
11-07 15:21:23.566  2538  2766 I vol.Events: writeEvent external_ringer_mode_changed normal
11-07 15:21:23.568  1598  1598 V SettingsProvider: Notifying for 0: content://settings/global/zen_mode_config_etag
11-07 15:21:23.571  2538  2766 I vol.Events: writeEvent zen_mode_changed off
11-07 15:21:23.572  1598  1598 V SettingsProvider: Notifying for 0: content://settings/global/zen_mode

```

I don't find anything 'zen_mode'-like when rebooting
(I can only debug on Windows at the moment)
And I can't find "mute_changed" or "external_ringer" when rebooting

P.S. Would I get rid of this if I installed LineageOS? (Which doesn't seem possible anyway ...)

**Comment by antweb** [comment]
> On my Galaxy A20e this app still doesn't work too.

That's unexpected. I did not get any reports from Samsung users and my Samsung test device sets/rests DND correctly (although it does not have a startup sound). Can you provide some more details?
- What's your Android version
- What carrier are you on / which startup jingle do you get
- Does manually enabling Do Not Disturb disable the startup sound?

**Comment by antweb** [comment]
> Yes it's silent with DND enabled. Here is what happens when enabling/disabling DND:

Just to clarify, are these logs from you manually enabling/disabling Do Not Disturb in your settings?

> I don't find anything 'zen_mode'-like when rebooting (I can only debug on Windows at the moment) And I can't find "mute_changed" or "external_ringer" when rebooting

And when you talk about rebooting, you mean Silent Boot?

> P.S. Would I get rid of this if I installed LineageOS? (Which doesn't seem possible anyway ...)

Most likely, yes. But I haven't looked into it in a while. Last time I checked, you could either use a ROM with a different boot animation or get system write access to remove the sound file that is played on boot.

**Comment by ghost** [comment]
I installed SB again, and now it works. I'm sorry. Thanks a lot!

**Comment by hurzl** [comment]
> I installed SB again, and now it works. I'm sorry. Thanks a lot!

I'm sorry I did the same and have a completely different app without options anymore and it simply works now! I was absolutely sure I had the latest version (which is so old already) ...

**Comment by antweb** [comment]
> I installed SB again, and now it works. I'm sorry. Thanks a lot!

Since you have a Samsung, I highly suspect one of the battery optimizations kicked in. It's a massive headache.
Thank you for reporting your problems.

**Comment by antweb** [comment]
> > I installed SB again, and now it works. I'm sorry. Thanks a lot!
> 
> I'm sorry I did the same and have a completely different app without options anymore and it simply works now! I was absolutely sure I had the latest version (which is so old already) ...

Alright! That means you were still on 2.x.

**Comment by hurzl** [comment]
Maybe it happened because I had the previous version installed by source, then the new apk just didn't install over it but I somehow didn't recognize that. It only updated now after uninstalling the old version.
